version: 2.1
jobs:
  build:
    docker:
      - image: alpine/git
        auth:
          username: armangh24
          password: AR1223334444
    steps:
        - checkout
        - run: mkdir starter-nestjs
        - run: |
            cd starter-nestjs && ls
            git init
        # - run: ls
        # - run: 
        # - run: git remote add github https://github.com/Arman2409/starter-nestjs.git
        # - run: git config pull.rebase true
        # - run: git pull github main