version: 2.1
jobs:
  build:
    docker:
      - image: node/alpline
        auth:
          username: mydockerhub-user  # can specify string literal values
          password: $DOCKERHUB_PASSWORD  #
    steps:
        - checkout
        - run: npm run build