version: 2.1
jobs:
  build:
    docker:
      - image: node/alpline
        auth:
          username: armangh24
          password: AR1223334444
    steps:
        - checkout
        - run: npm run build